name = "r2-image-worker"
workers_dev = true

compatibility_date = "2024-09-02"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'images'
preview_bucket_name = 'images'

[placement]
mode = "smart"

[observability]
enabled = true